version: 0.2
- name: Download Apache Maven 
  get_url: url=http://apache.claz.org/maven/maven-3/3.1.1/binaries/apache-maven--bin.tar.gz dest=/tmp/apache-maven-3.1.1-bin.tar.gz

- name: Untar Maven 
  shell: chdir=/tmp creates=/opt/apache-maven-3.1.1 tar -zxf apache-maven-3.1.1-bin.tar.gz -C /opt

- name: Update path for maven use
  shell: export PATH=/opt/apache-maven-3.1.1/bin:$PATH
  
phases:
  install:
    runtime-versions:
      java: openjdk8
  build:
    commands:
      - java -version
      - mvn package
artifacts:
  files:
    - '**/*'
  base-directory: 'target/my-sample-html-app'
